### PR TITLE
add conditional statement

### PR DESCRIPTION
**Pull request by CPernet**
ecat validation remains unchanged by adding this statement

----
📚 Documentation preview 📚: https://pet2bids--271.org.readthedocs.build/en/271/

### CODE REVIEW

**Review by mnoergaard — COMMENTED** [review]
This looks good to me - I have asked @bendhouseart to carry out a few more tests also comparing with Turku's ecat2nii, so he might have additional feedback.

**Comment by CPernet** [comment]
@mnoergaard actually needs to be the other way around -- all our phantoms seems calibrated !

**Comment by bendhouseart** [comment]
It's beautiful ```> In ecat2nii (line 334) 
Warning: it looks like the source data are already dose calibrated - ecat2nii is thus not scaling the data 
> In ecat2nii (line 339) 
```

**Comment by bendhouseart** [comment]
Alright, the Nii's produced by this look like they're scaling to the same range as the original ecats viewed in Vinci and as the outputs from Turku. Below is a comparison of the the outputs from a previous commit on this branch compared to the current status 2165535 done in freeview:

Screenshot 2024-02-16 at 11 08 58 AM

Looks good to me 👍

**Review by bendhouseart — APPROVED** [review]

**Pull request merged**
